language:
  - cpp

os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  if [ ${TRAVIS_OS_NAME} = 'linux' ]; 
  then 
    sudo apt-get update;
    sudo apt-get install gcc-5 g++-5;
  fi
 
install:

script:
