language: cpp

os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  if [ ${TRAVIS_OS_NAME} = 'linux' ]; 
  then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo apt-get update;
    sudo apt-get install gcc-5 g++-5;
    sudo apt-get install libboost-all-dev;
  fi

install:
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10; fi
  - echo $CXX
  - echo $PWD

script: "./scripts/buildAndTest.sh"
